name: Code Checks

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    name: Code Checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-code-checks

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
        
      - name: Run PHPStan
        run: php vendor/bin/phpstan analyse --autoload-file tests/bootstrap.php
